- hosts: all

  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
  tasks:
    - name: Deploy SSH Key
      authorized_key: user=todd
        key="{{ lookup('file', '/home/todd/.ssh/id_rsa.pub') }}"
        state=present

    - include: tasks/packages.yml
    - include: tasks/erlang.yml
    - include: tasks/copy_ssh_keys.yml
  handlers:
    - name: restart ssh
      service:
        name=sshd
        state=restarted



