- hosts: all
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
  roles:
   - ericsysmin.docker.docker
   - geerlingguy.rabbitmq
   - kevincoakley.neo4j
   - andrewrothstein.minikube
   - geerlingguy.redis
#   - alban.andrieu.dropbox
#   - jaredhocutt.jetbrains_toolbox
  vars_files:
    - vars/desktop-apps.yml
  tasks:
    - include: tasks/copy_neo4j_apoc_plugin.yml
    - include: tasks/create_rabbit_user.yml
    - include: tasks/add_user_to_groups.yml
    - include: tasks/zsh.yml
