- hosts: localhost
  become: true
  pre_tasks:
    - name: update repositories
      apt: update_cache=yes
      changed_when: False
  vars_files:
    - vars/desktop-apps.yml
  tasks:
    - include: tasks/packages.yml
  
