- name: Copy public key
  copy:
    src: /home/todd/.ssh/id_rsa.pub
    dest: /home/todd/.ssh
    owner: todd
    group: todd
    mode: u+rw,g+r,o+r


- name: Copy private key
  copy:
    src: /home/todd/.ssh/id_rsa
    dest: /home/todd/.ssh
    owner: todd
    group: todd
    mode: u+rw,g-r,o-r