- name: Enable firewalld
  service: name=firewalld state=started enabled=yes
- firewalld:
    service: https
    permanent: yes
    state: enabled
- firewalld:
    port: 8080/tcp
    permanent: yes
    state: enabled
- firewalld:
    port: 22/tcp
    permanent: yes
    state: enabled
- firewalld:
    port: 5672/tcp
    permanent: yes
    state: enabled
- firewalld:
    port: 7474/tcp
    permanent: yes
    state: enabled
- firewalld:
    port: 7687/tcp
    permanent: yes
    state: enabled
