- name: "Install Packages"
  apt:
    pkg:
      - htop
      - mc
      - curl
      - xclip
      - zip
      - unzip
      - qemu-kvm
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
      - git
      - zsh
    state: present


