
- name: Check if .zshrc exists
  stat:
    path: ~/.zshrc
  register: stat_rc_result
  become: yes
  become_user: todd

- name: Check if .oh-my-zsh exists
  stat:
    path: ~/.oh-my-zsh
  register: stat_oh_my_zsh_result
  become: yes
  become_user: todd

- name: Cloning  oh-my-zsh
  git:
    repo=https://github.com/robbyrussell/oh-my-zsh
    dest=~/.oh-my-zsh
  when: not stat_oh_my_zsh_result.stat.exists
  become: yes
  become_user: todd

- name: Creating new ~/.zshrc
  copy:
    src=~/.zshrc
    dest=~/.zshrc
  when: not stat_rc_result.stat.exists
  become: yes
  become_user: todd
